"use client";

import AppShell from "./AppShell";
import AffiliatesTable from "./AffiliatesTable";
import { stages } from "../app/dashboard-data";

export default function DashboardPage() {
  return <AppShell><div className="content-wrap"><section className="welcome-row"><div><p className="eyebrow">TERÇA-FEIRA, 15 DE SETEMBRO DE 2026</p><h1>Bom dia, Joana<span className="sun">✳</span></h1><p className="subheading">Aqui está o panorama do seu programa hoje.</p></div><button className="primary-button" type="button" onClick={() => document.getElementById("new-affiliate-button")?.click()}>+ <span>Nova afiliada</span></button></section><section className="metrics-grid" aria-label="Resumo do programa"><article className="metric-card accent"><span className="metric-label">Afiliadas ativas <b>↗</b></span><strong>22</strong><small>+3 neste mês</small><div className="sparkline"><i /><i /><i /><i /><i /><i /><i /></div></article><article className="metric-card"><span className="metric-label">Em processo <b>↗</b></span><strong>23</strong><small>8 em análise</small><div className="metric-dots"><i /><i /><i /><i /><i /><i /></div></article><article className="metric-card"><span className="metric-label">Pendências <b>↗</b></span><strong>09</strong><small className="warning-text">3 vencem esta semana</small><div className="metric-bars"><i /><i /><i /><i /><i /></div></article><article className="metric-card"><span className="metric-label">A receber <b>↗</b></span><strong>R$ 48.600</strong><small>4 cobranças em aberto</small><div className="metric-line" /></article></section><section className="overview-grid"><div className="panel pipeline-panel"><div className="panel-heading"><div><p className="eyebrow">ACOMPANHAMENTO</p><h2>Processos por etapa</h2></div><a className="text-button" href="/afiliadas">Ver pipeline <span>→</span></a></div><div className="stage-list">{stages.map(([label, amount, description], index) => <div className="stage" key={label}><div className={`stage-number n-${index}`}>{amount}</div><div className="stage-copy"><strong>{label}</strong><span>{description}</span></div><div className="stage-arrow">›</div></div>)}</div></div><div className="panel attention-panel"><div className="panel-heading"><div><p className="eyebrow">PARA HOJE</p><h2>Requer atenção</h2></div><span className="attention-badge">4 itens</span></div><div className="attention-list"><div><span className="attention-icon orange">!</span><span><strong>Documentos pendentes</strong><small>Bioma Circular e mais 4</small></span><b>→</b></div><div><span className="attention-icon blue">$</span><span><strong>Pagamentos próximos</strong><small>2 vencem nos próximos 7 dias</small></span><b>→</b></div><div><span className="attention-icon green">✓</span><span><strong>Retorno da Procuradoria</strong><small>1 contrato aguardando retorno</small></span><b>→</b></div></div></div></section><AffiliatesTable compact /></div></AppShell>;
}
